name: Build
on:
  push:
    branches:
      - dev
    tags: ["v*"]
    paths:
      - Jellyfin.Plugin.Pronium/**
      - .github/**

jobs:
  jellyfin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release

      - name: Rename Files
        run: ren Jellyfin.Plugin.Pronium/bin/Release/net6.0/Pronium.dll Jellyfin.Plugin.Pronium.dll && ren Jellyfin.Plugin.Pronium/bin/Release/net6.0/Pronium.pdb Jellyfin.Plugin.Pronium.pdb

      - uses: vimtor/action-zip@v1
        with:
          files: Jellyfin.Plugin.Pronium/bin/Release/net6.0/Jellyfin.Plugin.Pronium.pdb Jellyfin.Plugin.Pronium/bin/Release/net6.0/Jellyfin.Plugin.Pronium.dll
          dest: Jellyfin.Plugin.Pronium.zip

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Jellyfin
          retention-days: 90
          path: Jellyfin.Plugin.Pronium.zip
  emby:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release.Emby

      - name: Rename Files
        run: ren Jellyfin.Plugin.Pronium/bin/Release.Emby/netstandard2.1/Pronium.dll ./Emby.Plugins.Pronium.dll && ren Jellyfin.Plugin.Pronium/bin/Release.Emby/netstandard2.1/Pronium.pdb ./Emby.Plugins.Pronium.pdb

      - uses: vimtor/action-zip@v1
        with:
          files: Jellyfin.Plugin.Pronium/bin/Release.Emby/netstandard2.1/Emby.Plugins.Pronium.pdb Jellyfin.Plugin.Pronium/bin/Release.Emby/netstandard2.1/Emby.Plugins.Pronium.dll
          dest: Emby.Plugins.Pronium.zip

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Emby
          retention-days: 90
          path: Emby.Plugins.Pronium.zip
  deploy:
    runs-on: ubuntu-latest
    needs: [jellyfin, emby]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            **/Jellyfin.Plugin.Pronium.zip
            **/Emby.Plugins.Pronium.zip
